// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appContainer': string;
  'appHeader': string;
  'appRoot': string;
  'other-frontend': string;
}
export const cssExports: CssExports;
export default cssExports;
