// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'banner-title': string;
  'cat': string;
  'content': string;
  'dog': string;
  'home': string;
}
export const cssExports: CssExports;
export default cssExports;
